satmap/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ProjectList.as_view(), name='project_list'),
    path('project/create/', views.ProjectCreate.as_view(), name='project_create'),
    path('project/<int:pk>/', views.ProjectDetail.as_view(), name='project_detail'),
    path('project/edit/<int:pk>/', views.ProjectUpdate.as_view(), name='project_edit'),
    path('project/duplicate/<int:pk>/', views.ProjectDuplicate.as_view(), name='project_duplicate'),
    path('project/delete/<int:pk>/', views.ProjectDelete.as_view(), name='project_delete'),
    path('map/create/', views.MapCreate.as_view(), name='map_create'),
    path('map/<int:pk>/', views.MapDetail.as_view(), name='map_detail'),
    path('map/array/<int:pk>/', views.MapArray.as_view(), name='map_array'),
    path('map/split/<int:pk>/', views.MapSplit.as_view(), name='map_split'),
    path('map/timeseries/<int:pk>/', views.MapTimeSeries.as_view(), name='map_split'),
    path('map/edit/<int:pk>/', views.MapUpdate.as_view(), name='map_edit'),
    path('map/duplicate/<int:pk>/', views.MapDuplicate.as_view(), name='map_duplicate'),
    path('map/delete/<int:pk>/', views.MapDelete.as_view(), name='map_delete'),
    path('layers', views.LayerList.as_view(), name='layer_list'),
    path('layer/create/', views.LayerCreate.as_view(), name='layer_create'),
    path('layer/<int:pk>/', views.LayerDetail.as_view(), name='layer_detail'),
    path('layer/edit/<int:pk>/', views.LayerUpdate.as_view(), name='layer_edit'),
    path('layer/delete/<int:pk>/', views.LayerDelete.as_view(), name='layer_delete'),
    path('request-account', views.RequestAccount.as_view(), name='request_account')
]

satmap/models.py
import ee
import folium

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.postgres.fields import ArrayField

from .utils import initialize_gee

from location_field.models.plain import PlainLocationField

class Layer(models.Model):
    name = models.CharField(max_length=255)
    code = models.CharField(max_length=255)
    band = models.CharField(max_length=255)
    min = models.DecimalField(max_digits=10,
        decimal_places=3, blank=True, null=True)
    max = models.DecimalField(max_digits=10,
        decimal_places=3, blank=True, null=True)
    opacity = models.DecimalField(max_digits=3, decimal_places=2, default=0.5, validators=[
            MinValueValidator(0),
            MaxValueValidator(1)])
    #palette = ArrayField(models.CharField(max_length=255), default=['blue', 'purple', 'cyan', 'green', 'yellow', 'red'])
    palette = models.TextField(default = "[ 'blue', 'purple', 'cyan', 'green', 'yellow', 'red' ]")
    units = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)
    is_collection = models.BooleanField(default=True)

    class Meta:
        ordering = ['name']

    def get_array_params(self):
        params = {}
        for field in ['min', 'max','opacity']:
            if getattr(self, field):
                params[field] = float(getattr(self,field))
        params['dimensions'] = '400x400'
        return params

    def get_vis_params(self):
        params = {}
        for field in ['min', 'max','opacity']:
            if getattr(self, field):
                params[field] = float(getattr(self,field))
        if self.palette:
            params['palette'] = self.get_palette_list()
        return params

    def __str__(self):
        return self.name
    
    def get_palette_list(self):
        palette = self.palette.split(', ')
        palettelist = []
        for color in palette:
            palettelist.append(color[7:-5])
        return palettelist

class Project(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    latitude = models.DecimalField(max_digits=17, decimal_places=14, blank=True)
    longitude = models.DecimalField(max_digits=17, decimal_places=14, blank=True)
    location = PlainLocationField(based_fields=['city'], zoom=7)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    datasets = models.ManyToManyField(Layer, blank=True)

    class Meta:
        ordering = ['name']
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('project_detail', kwargs={'pk':self.id})
    
    def save(self, *args, **kwargs):
        if not self.latitude:
            self.latitude, self.longitude = self.location.split(',')
        for map in self.map_set.all():
            for layer in self.datasets.all():
                map.layer.add(layer)
            map.save()
        super(Project, self).save(*args, **kwargs)

class Rectangle(models.Model):
    southwest = models.DecimalField(max_digits=9, decimal_places=6)

class Map(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, 
        blank=True, null=True)
    title = models.CharField(max_length=200, blank=True)
    description = models.TextField(blank=True)
    latitude = models.DecimalField(max_digits=17, decimal_places=14, blank=True)
    longitude = models.DecimalField(max_digits=17, decimal_places=14, blank=True)
    location = PlainLocationField(based_fields=['city'], zoom=7)
    zoom = models.IntegerField(default=8)
    layer = models.ManyToManyField(Layer, blank=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        ordering = ['title']
    
    def save(self, *args, **kwargs):
        if not self.latitude:
            self.latitude, self.longitude = self.location.split(',')
        super(Map, self).save(*args, **kwargs)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        if self.project:
            return self.title + ' (' + self.project.name + ')'
        else:
            return self.title
    
    def duplicate(self, project):
        map = Map.objects.create(
            project = project,
            title = self.title,
            description = self.description,
            location = self.location,
            zoom = self.zoom,
            start_date = self.start_date,
            end_date = self.end_date,
            published_date = self.published_date
        )
        map.layer.set(self.layer.all())

    def get_array(self):
        initialize_gee()


class MapRender(models.Model):
    map = models.ForeignKey(Map, on_delete=models.CASCADE)
    html = models.TextField(blank=True)
    date = models.DateField(blank=True, null=True)

    def __str__(self):
        if self.date:
            return '{}: {}'.format(self.map.title, self.date)

satmap/views.py
import folium

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone
from django.urls import reverse
from django.views.generic import View, DetailView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .forms import LayerForm, MapForm, ProjectForm
from .models import Layer, Map, Project

from .utils import initialize_gee
from folium import plugins

from datetime import datetime

import ee

class MapView(LoginRequiredMixin, View):
    model = Map
    form_class = MapForm
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

class MapDetail(MapView, DetailView):
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        initialize_gee()
        # Define an image.
        map = self.get_object()
        figure = folium.Figure()
        
        # mapbox_satellite_url = "https://api.mapbox.com/styles/v1/mapbox/satellite-v9/tiles/256/{z}/{x}/{y}@2x?access_token={}".format(settings.MAPBOX_KEY)
        mapbox_satellite_url = 'https://api.mapbox.com/styles/v1/mapbox/satellite-v9/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1Ijoic2FyYWFiaSIsImEiOiJjbGxvYmpxYWMwNzR4M2luM2FhMTBtMDFwIn0.dtam9tTkw1w0b88z-c_BDA'

        #create Folium Object
        m = folium.Map(
            location=[map.latitude, map.longitude], 
            tiles=mapbox_satellite_url, 
            attr='Mapbox',
            zoom_start=map.zoom
        )

        #add map to figure
        m.add_to(figure)

        dates = []

        for layer_instance in map.layer.all():
            #select the Dataset Here's used the MODIS data
            if layer_instance.is_collection:
                datasets = (ee.ImageCollection(layer_instance.code).filter(
                    ee.Filter.date(
                        map.start_date.strftime('%Y-%m-%d'),
                        map.end_date.strftime('%Y-%m-%d')
                    )).sort('system:time_start', False))
                dataset = datasets.first()
                dates += datasets.aggregate_array('system:time_start').getInfo()
            else:
                dataset = (ee.Image(layer_instance.code))
                dates.append(dataset.get('system:time_start').getInfo())
            
            layer = dataset.select(layer_instance.band)

            vis_params = layer_instance.get_vis_params()
            
            #add the map to the the folium map
            map_id_dict = ee.Image(layer).getMapId(vis_params)
        
            #GEE raster data to TileLayer
            folium.raster_layers.TileLayer(
                        tiles = map_id_dict['tile_fetcher'].url_format,
                        attr = 'Google Earth Engine',
                        name = layer_instance.name,
                        overlay = True,
                        control = True
                        ).add_to(m)
        
        #add Layer control
        m.add_child(folium.LayerControl())

        python_dates = []
        for date in dates:
            python_date = datetime.utcfromtimestamp(date / 1000.0).strftime('%Y-%m-%d')
            python_dates.append(python_date)
        
        context['folium_map'] = figure.render()
        context['dates'] = python_dates
        return context

class MapArray(MapView, DetailView):
    template_name = 'satmap/map_array.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        initialize_gee()
        # Define an image.
        map = self.get_object()

        mapbox_satellite_url = 'https://api.mapbox.com/styles/v1/mapbox/satellite-v9/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1Ijoic2FyYWFiaSIsImEiOiJjbGxvYmpxYWMwNzR4M2luM2FhMTBtMDFwIn0.dtam9tTkw1w0b88z-c_BDA'
        
        roi = ee.Geometry.Rectangle([106.81405, 2.88569, 106.97828, 43.01367])
        vis_params = map.layer.first().get_array_params()
        datasets= ee.ImageCollection('COPERNICUS/S2') \
            .filterBounds(roi) \
            .filterDate(map.start_date.strftime('%Y-%m-%d'), map.end_date.strftime('%Y-%m-%d')) \
            .filter(ee.Filter.calendarRange(8, 8, 'month')) \
            .sort('system:time_start', True)
        
        timestamps = list(set([img['properties']['system:time_start'] \
            for img in datasets.getInfo()['features']]))
        timestamps.sort()

        map_data = []
        

        for timestamp in timestamps:
            # Filter the dataset for the current timestamp and get the first image.
            img_obj = ee.ImageCollection('COPERNICUS/S2') \
                .filterBounds(roi) \
                .filterDate(map.start_date.strftime('%Y-%m-%d'), map.end_date.strftime('%Y-%m-%d')) \
                .filter(ee.Filter.calendarRange(8, 8, 'month')) \
                .filter(ee.Filter.eq('system:time_start', timestamp)) \
                .first()
            mapid = img_obj.getMapId(vis_params)
            timestamp = img_obj.getInfo()['properties']['system:time_start']  # Adjust DATE_PROPERTY to your dataset's date property
            date = datetime.fromtimestamp(timestamp / 1000)
            m = folium.Map(
                location=[map.latitude, map.longitude], 
                tiles=mapbox_satellite_url, 
                attr='Mapbox',
                zoom_start=map.zoom
            )
            folium.TileLayer(
                tiles=mapid['tile_fetcher'].url_format,
                attr='Google Earth Engine',
                overlay=True,
                control=True
            ).add_to(m)
            map_html = m._repr_html_()
            print(map_html)
            map_data.append({'map': map_html, 'date': date})
        context['maps'] = map_data
        
       
        return context
    
class MapSplit(MapView, DetailView):
    template_name = 'satmap/map_split.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Define an image.
        map = self.get_object()
        initialize_gee()
        figure = folium.Figure()
        
        #create Folium Object
        m = plugins.DualMap(
            location=[map.latitude, map.longitude], 
            zoom_start=map.zoom
        )

        layer_one = map.layer.first()
            #select the Dataset Here's used the MODIS data
        dataset = (ee.ImageCollection(layer_one.code).filter(
            ee.Filter.date(
                map.start_date.strftime('%Y-%m-%d'),
                map.end_date.strftime('%Y-%m-%d')
            )).first())
        layer = dataset.select(layer_one.band)
        
        vis_params = layer_one.get_vis_params()
        
        #add the map to the the folium map
        map_id_dict = ee.Image(layer).getMapId(vis_params)
    
        #GEE raster data to TileLayer
        folium.raster_layers.TileLayer(
                    tiles = map_id_dict['tile_fetcher'].url_format,
                    attr = 'Google Earth Engine',
                    name = layer_one.name,
                    overlay = True,
                    control = True
                    ).add_to(m.m1)
        
        layer_two = map.layer.first()
            #select the Dataset Here's used the MODIS data
        collection = ee.ImageCollection(layer_two.code).filter(
            ee.Filter.date(
                map.start_date.strftime('%Y-%m-%d'),
                map.end_date.strftime('%Y-%m-%d')
            ))
        latest = collection.sort('system:time_start', False).first()
        layer = latest.select(layer_two.band)

        vis_params = layer_two.get_vis_params()
        
        #add the map to the the folium map
        map_id_dict = ee.Image(layer).getMapId(vis_params)
    
        #GEE raster data to TileLayer
        folium.raster_layers.TileLayer(
                    tiles = map_id_dict['tile_fetcher'].url_format,
                    attr = 'Google Earth Engine',
                    name = layer_two.name,
                    overlay = True,
                    control = True
                    ).add_to(m.m2)

        # m = m._repr_html_()
        # m.add_to(figure)
        # figure.render()
        # figure_html = figure._repr_html_()
        m.add_child(folium.LayerControl())
        context['folium_map'] = m._repr_html_()
        return context
    
class MapTimeSeries(MapView, DetailView):
    template_name = 'satmap/map_split.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Define an image.
        map = self.get_object()
        initialize_gee()

        figure = folium.Figure()
        
        # mapbox_satellite_url = "https://api.mapbox.com/styles/v1/mapbox/satellite-v9/tiles/256/{z}/{x}/{y}@2x?access_token={}".format(settings.MAPBOX_KEY)
        mapbox_satellite_url = 'https://api.mapbox.com/styles/v1/mapbox/satellite-v9/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1Ijoic2FyYWFiaSIsImEiOiJjbGxvYmpxYWMwNzR4M2luM2FhMTBtMDFwIn0.dtam9tTkw1w0b88z-c_BDA'

        #create Folium Object
        m = folium.Map(
            location=[map.latitude, map.longitude], 
            tiles=mapbox_satellite_url, 
            attr='Mapbox',
            zoom_start=map.zoom
        )
        
        for layer_instance in map.layer.all():
            #select the Dataset Here's used the MODIS data
            dataset = (ee.ImageCollection(layer_instance.code).filter(
                ee.Filter.date(
                    map.start_date.strftime('%Y-%m-%d'),
                    map.end_date.strftime('%Y-%m-%d')
                )))
            print('SIZE: {}'.format(dataset.size().getInfo()))
            print('COUNT: {}'.format(dataset.count()))
            print(dataset.__dict__)
            layer = dataset.select(layer_instance.band)

            vis_params = layer_instance.get_vis_params()
            

satmap/templates/satmap/layer_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h2>Confirm Layer Deletion</h2>
  <p>Are you sure you want to delete the layer "{{ layer.name }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
    <a href="{% url 'layer_detail' pk=layer.pk %}">Cancel</a>
  </form>
{% endblock %}

satmap/templates/satmap/layer_detail.html
{% extends 'base.html' %}

{% block content %}
    <article class="post">
        <aside class="actions">  
            {% if user.is_authenticated %}
                <a class="btn btn-secondary" href="">
                </a>
            {% endif %}
        </aside>
        <div class="header">
            <h2>{{ layer.name }}{% if layer.units %} ({{ layer.units }}){% endif %}</h2>
            <div class="icon-container">
                <a class="Icon" href="{% url 'layer_edit' pk=layer.pk %}"><i class="fa-light fa-pencil" title="Edit Layer"></i></a> 
                <a class="Icon" href="{% url 'layer_delete' pk=layer.pk %}"><i class="fa-regular fa-trash-can" title="Delete Layer"></i></a>
            </div>
        </div>
        <p>{{ layer.description }}</p>
    </article>
{% endblock %}

satmap/templates/satmap/layer_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    
    <h2>{% if request.resolver_match.url_name == 'layer_edit'  %} Edit {% else %} New {% endif %} Layer</h2>
    <form method="POST" class="layer-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
{% endblock %}

satmap/templates/satmap/layer_list.html
{% extends 'base.html' %}

{% block content %}
	<p>
	<br> Search <a href="https://developers.google.com/earth-engine/datasets/catalog">Google Earth Engine</a> for potential layers. Create a new layer using this button, or click on one of the existing layers below to view and edit it. 
	<br>
	<br><a href="{% url 'layer_create' %}"><button class="btn btn-primary">Create Layer</button></a>
	<br>
	<br>
	</p>
	{% for layer in layer_list %}
		<article>
			<div class="header">
				<h3><a href="{% url 'layer_detail' pk=layer.pk %}">{{ layer.name }}</a></h3>
				<div class="icon-container">
					<a class="Icon" href="{% url 'layer_edit' pk=layer.pk %}"><i class="fa-light fa-pencil" title="Edit"></i></a> 
					<a class="Icon" href="{% url 'layer_delete' pk=layer.pk %}"><i class="fa-regular fa-trash-can"></i></a>
				</div>
			</div>
			<p>{{ project.description|linebreaksbr }}</p>
			<p><b></p>
		</article>
	{% endfor %}
{% endblock %}

satmap/templates/satmap/map_array.html
{% extends 'base.html' %}

{% block head %}
<style>
    p {
        font-weight:600;
    }
</style>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"/>
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>


{% endblock %}

{% block content %}
    <h2>SPLIT MAP: {{ map.title }}</h2>
    <p>{{ map.description }}</p>
    <p><b></p>
    <a href="{% url 'map_edit' pk=map.pk %}"><button class="btn btn-primary">Edit Map</button></a>
    <a href="{% url 'map_duplicate' pk=map.pk %}?project={{ map.project.id }}"><button class="btn btn-primary">Duplicate Map</button></a>
    <a href="{% url 'map_delete' pk=map.pk %}"><button class="btn btn-primary">Delete Map</button></a>
    <p><b></p>
    <!-- <article class="post">
        <aside class="actions">  
            {% if user.is_authenticated %}
                <a class="btn btn-secondary" href=""">
                    
                </a>
            {% endif %}
        </aside>
        {% if map.published_date %}
            <time class="date">
                {{ map.published_date }}
            </time>
        {% endif %}
        <h2>{{ map.title }} - {{ url }}</h2>
        <p>Coordinates: {{ map.latitude }}, {{ map.longitude|linebreaksbr }}</p>
    </article> -->
    <div class="d-flex flex-wrap">
    {% for map_info in maps %}
    <div style="flex:1 1 400px;">
        {{ map_info.map|safe }}
        {{ map_info.date }}
    </div>
    {% endfor %}
    </div>
    <!-- <div id="map{{ map.id }}" class="map"></div>
    <script>
        function initMap() {
            // Create a map object
           
            const map = new google.maps.Map(document.getElementById("map{{ map.id }}"), {
                zoom: 4,
                center: {lat: 0, lng: 0}
            });

            var geeLayer = new google.maps.GroundOverlay(
                "{{ url }}",
                {north: 80, south: -80, east: 180, west: -180},
                {opacity: 0.5}
                );

                geeLayer.setMap(map);
        }
        initMap();
    </script> -->
    <script>
 
    </script>
{% endblock %}

satmap/templates/satmap/map_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h2>Confirm Map Deletion</h2>
  <p>Are you sure you want to delete the map "{{ map.title }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
    <a href="{% url 'map_detail' pk=map.pk %}">Cancel</a>
  </form>
{% endblock %}

satmap/templates/satmap/map_detail.html
{% extends 'base.html' %}

{% block content %}
    <a href="{% url 'project_detail' pk=map.project.pk %}"><button class="btn btn-link">Back to Project</button></a>
    <div class="header">
        <h2>{{ map.title }}</h2>
        <div class="icon-container">
            <a href="{% url 'map_edit' pk=map.pk %}"><i class="fa-light fa-pencil" title="Edit Map"></i></a>
            <a href="{% url 'map_duplicate' pk=map.pk %}?project={{ map.project.id }}"><i class="fa-regular fa-copy" title="Duplicate Map"></i></a>
            <a href="{% url 'map_delete' pk=map.pk %}"><i class="fa-regular fa-trash-can" title="Delete Map"></i></a>
        </div>
    </div>
    <p class="py-3">{{ map.description }}</p>
    

    <!-- <article class="post">
        <aside class="actions">  
            {% if user.is_authenticated %}
                <a class="btn btn-secondary" href=""">
                    
                </a>
            {% endif %}
        </aside>
        {% if map.published_date %}
            <time class="date">
                {{ map.published_date }}
            </time>
        {% endif %}
        <h2>{{ map.title }} - {{ url }}</h2>
        <p>Coordinates: {{ map.latitude }}, {{ map.longitude|linebreaksbr }}</p>
    </article> -->
    <div style="height:600px;width:100%">
        {{ folium_map|safe }}
    </div>
    <h3>{% if map.layer.all|length != 0 %}Map Data{% endif %}</h3>
    {% for layer in  map.layer.all %}
    <div class="py-3">
        <div class="accordion accordion-flush" id="accordion{{ layer.id }}">
            <div class="accordion-item">
              <h2 class="accordion-header" id="flush-heading{{ layer.id }}">
                <button class="accordion-button collapsed fs-3" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapse{{ layer.id }}" aria-expanded="false" aria-controls="flush-collapse{{ layer.id }}">
                    <strong>{{ layer.name }}{% if layer.units %} ({{ layer.units }}){% endif %}</strong>
                </button>
              </h2>
              <div id="flush-collapse{{ layer.id }}" class="accordion-collapse collapse" aria-labelledby="flush-heading{{ layer.id }}" data-bs-parent="#accordion{{ layer.id }}">

                <div class="accordion-body">
                    {% for date in dates %}
                        {% if forloop.first %}
                            <p>{{ date }}</p>
                        {% endif %}
                    {% endfor %}
                    <p>{{ layer.description }}</p></div>
              </div>
            </div>
        </div>
            
        </div>
        <div class="d-flex w-100 py-3">
            <div style="flex:1;" class="text-center">{{ layer.min }}</div>
            {% for color in layer.get_palette_list %}
            <div style="flex:1;background-color: #{{ color }};"></div>
            {% endfor %}
            <div style="flex:1;" class="text-center">{{ layer.max }}</div>
        </div>
    </div>


    
    {% endfor %}
    <!-- <div id="map{{ map.id }}" class="map"></div>
    <script>
        function initMap() {
            // Create a map object
           
            const map = new google.maps.Map(document.getElementById("map{{ map.id }}"), {
                zoom: 4,
                center: {lat: 0, lng: 0}
            });

            var geeLayer = new google.maps.GroundOverlay(
                "{{ url }}",
                {north: 80, south: -80, east: 180, west: -180},
                {opacity: 0.5}
                );

                geeLayer.setMap(map);
        }
        initMap();
    </script> -->

   
{% endblock %}

satmap/templates/satmap/map_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h2>{% if request.resolver_match.url_name == 'map_edit'  %} Edit {% else %} New {% endif %} Map</h2>
    <form method="POST" class="map-form w-75">{% csrf_token %}
        {{form.media}}
        {{ form|crispy }}

        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
{% endblock %}

{% block javascript %}
<script>
    $( function() {
        $( "#datepicker_start" ).datepicker();
        $( "#datepicker_end" ).datepicker();
    } );

  </script>
{% endblock %}

satmap/templates/satmap/project_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h2>Confirm Project Deletion</h2>
  <p>Are you sure you want to delete the project "{{ project.name }}"?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
    <a href="{% url 'project_detail' pk=project.pk %}">Cancel</a>
  </form>
{% endblock %}

satmap/templates/satmap/project_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    
    <h2>{% if request.resolver_match.url_name == 'project_edit'  %} Edit {% else %} New {% endif %} Project</h2>
    <form method="POST" class="project-form w-75">{% csrf_token %}
        {{form.media}}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-secondary">Save</button>
    </form>
{% endblock %}

{% block javascript %}
<script>
    $( function() {
        $( "#datepicker_start" ).datepicker();
        $( "#datepicker_end" ).datepicker();
    } );

  </script>
{% endblock %}

satmap/templates/satmap/request_account.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    
    <h2>Request Account</h2>
    <form method="POST" class="w-50">{% csrf_token %}
        <label for="id_name" class="form-label mt-4">Name</label>
        <input type="text" class="form-control" name="name" id='id_name'>
        <label for="id_email" class="form-label mt-4">Email address</label>
        <input type="email" class="form-control" name="email" id='id_email'>
        <label for="id_text" class="form-label mt-4">Why do you want an account?</label>
        <textarea class="form-control" name="text" id='id_text'></textarea>
        <button type="submit" class="save btn btn-secondary mt-4">Save</button>
    </form>
{% endblock %}